### ISSUE TITLE
Uninstall puro?

### ISSUE THREAD

**Issue by thilojaeggi** [pingbird/puro#14]
I've deleted the directory but the PATH variable stays.
How can I remove it?

**Comment by thilojaeggi** [comment]
It's in .zprofile, my bad 🤦

**Comment by pingbird** [comment]
I can probably add an uninstall command but the only thing it touches is ~/.puro and your bash or zsh profile

**Comment by getBoolean** [comment]
I noticed the cache path still points to `C:\Users\user\.puro\shared\pub_cache\bin` even after uninstalling puro and using fvm or normal flutter sdk. How do I change it back?

**Comment by pingbird** [comment]
Environment variables on windows can be found here:

![image](https://github.com/pingbird/puro/assets/2466461/6ad66a0c-119a-4e81-a44e-3a63835b67c4)

Gonna reopen this issue, ideally you shouldn't have to dig through settings like this 😭

**Comment by pingbird** [comment]
The next release adds a `puro uninstall-puro` which should clean up environment variables for you.
