### ISSUE TITLE
Mark the pub.dev version as "DISCONTINUED" since it might mislead some new users

### ISSUE THREAD

**Issue by brainwo** [pingbird/puro#15]
https://discord.com/channels/420324994703163402/421445316617961502/1118978864945827964

**Comment by pingbird** [comment]
Marking the package unlisted would hurt SEO, I don't think they let you customize the installation instructions either :/

**Comment by brainwo** [comment]
> I don't think they let you customize the installation instructions either :/
I think you should be able to push a new README to the pub.dev
