### ISSUE TITLE
Puro recommends removing the following from your PATH

### ISSUE THREAD

**Issue by ondanplatform** [pingbird/puro#24]
but why? can you explain ? 

```
(base) mirzali@Mirzalis-MacBook-Pro my_project % puro version
[!] Other Flutter or Dart installations detected
    Puro recommends removing the following from your PATH:
    * /Users/mirzali/development/flutter/bin/dart
    * /Users/mirzali/development/flutter/bin/flutter
[i] Puro 1.3.2 (distribution/darwin-x64)
    Dart 2.19.5 (stable) (Mon Mar 20 17:09:37 2023 +0000) on "macos_x64"
```

**Comment by pingbird** [comment]
Puro manages your flutter installation, having a separate installation will make `puro use -g foo` ineffective depending on the order they were added to the PATH

**Comment by ondanplatform** [comment]
@pingbird I removed from zshrc. I have to remove from settings.json too ? If yes what will be then ? `dart.sdkPath` and `dart.flutterSdkPath` ? 

```
  "dart.sdkPath": "/Users/myname/development/flutter/bin/dart",
  "dart.flutterSdkPath": "/Users/myname/development/flutter",
```

**Comment by pingbird** [comment]
Those lines in the settings.json are unnecessary because the Flutter plugin can auto-detect which one to use in the PATH, delete them if you want. Puro can also update your settings.json automatically with the `puro use` command.

**Comment by dilshadxahmad** [comment]
> Puro manages your default flutter installation, having a separate installation will make `puro use -g foo` ineffective depending on the order they were added to the PATH

What to do on my windows pc? Just remove all the dart/flutter paths from the user env variables?
