### ISSUE TITLE
[Feature Request] Respect XDG Directory specification

### ISSUE THREAD

**Issue by realitymolder** [pingbird/puro#27]
Hey, been trying to use puro, It seems that after I've moved the binary according to the XDG spec it moved the installation back to 
 ~/.puro (HOME/.puro)

I think it would be very beneficial to give us the option to move the `puro home` to respect the XDG Base Directory specification.
Read more [here](https://wiki.archlinux.org/title/XDG_Base_Directory)

**Comment by pingbird** [comment]
To change the installation location set the PURO_ROOT environment variable, I am often typing environment paths manually which is why ~/.puro is the default

**Comment by realitymolder** [comment]
> To change the installation location set the PURO_ROOT environment variable, I am often typing environment paths manually which is why ~/.puro is the default

Thanks for the *very* fast reply!
I would suggest putting it in the docs, because I checked that before posting here and there is none.
