### ISSUE TITLE
Versioned environments

### ISSUE THREAD

**Issue by pingbird** [pingbird/puro#35]
A lot of users desire functionality similar to other version managers where you can do `puro use 2.10.4` instead of `puro create foo 2.10.4; puro use foo`. This is reasonable and can also be used as a mechanism to pin projects to a specific version (#33) making sure they are not upgraded on accident.

Versioned environments would work the same as the `stable` `beta` `master` environments which are lazily initialized to their equivalent version. Attempting an upgrade will warn the user to switch versions per-project.

**Comment by tksoh** [comment]
Does this feature mean we can do just `puro use 2.10.4` and puro would create the version 2.10.4 automatically if it's not already created? If so, this would be a great change.

I've always found puro's requiring users to provide a environment name rather annoying, especially given the current limitations on the naming convention. To me the env name should be optional.

**Comment by pingbird** [comment]
FYI this is next on my TODO list
