### ISSUE TITLE
no command to rename environment

### ISSUE THREAD

**Issue by tksoh** [pingbird/puro#37]
I'm unable to find the command to rename the environments I created earlier. Is it supported? If not, any way to get this done. Thanks.

**Comment by pingbird** [comment]
For now you can simply rename the folder or create a new environment with the same version, I recall not implementing a rename command because it would break any projects that depend on it (puro has no way of keeping track of per-project settings globally)

**Comment by tksoh** [comment]
@pingbird if renaming an environment would break projects depending on it, wouldn't 'puro rm' break those projects too? Same thing with us renaming the folder manually.

**Comment by pingbird** [comment]
That is correct, `puro rm` and renaming manually would break projects.

**Comment by tksoh** [comment]
@pingbird Just curious, would it be possible to maintain a map to track the rename, so that puro can look it up to find the new env? This way the projects still using the old env names will not break after the rename. Make sense?

**Comment by pingbird** [comment]
I added global project tracking to prevent `puro rm` from breaking projects and a new `puro rename` command that automatically updates configs. It will only work for projects that have been open *after* puro 1.3.6.

**Comment by pingbird** [comment]
Didn't add a rename command so this should probably still be open
