### ISSUE TITLE
Pub_Cache environment change issue

### ISSUE THREAD

**Issue by singhtaranjeet** [pingbird/puro#43]
puro sets "Pub_Cache" to .puro/shared/pub_cache
all my packages are using this now but for some reason i want to use .pub-cache of flutter not able to change that.

After uninstalling too my packages are using .puro folder rather then normal flutter .pub-cache/

**Comment by pingbird** [comment]
That is from PUB_CACHE.

Use `puro uninstall-puro` to clean up environment variables, otherwise you can do that manually by editing `~/.zshrc` (mac), `~/.bashrc` (linux), or the environment variables dialog in windows settings.
