### ISSUE TITLE
Allow fetching tags that are not in releases

### ISSUE THREAD

**Issue by feinstein** [pingbird/puro#44]
As the title says, `puro releases` is not showing version 3.10.7.

**Comment by pingbird** [comment]
That version doesn't exist anywhere else: https://docs.flutter.dev/release/archive?tab=windows

**Comment by feinstein** [comment]
We should have a `--tag` flag.

Sometimes the Flutter team releases old versions fixes they don't want to promote I think. 3.10.7 was one of those, they even made a migration document [here](https://github.com/flutter/flutter/wiki/Upgrading-from-3.10.6-to-3.10.7).

**Comment by feinstein** [comment]
@pingbird I am on puro 1.4.0 and I tried to run `puro create 3.10.7 3.10.7` but I get the error:

[x] Cannot initialize environment 3.10.7 with version e285328a6909879584a27c9b8eec5fa3621ead93

**Comment by pingbird** [comment]
@feinstein
Oops, the command turns 3.10.7 into a commit which trips a check later to prevent you from assigning an arbitrary release to environment 3.10.7 😢 
Just `puro create 3.10.7` or `puro use 3.10.7` should work, and the bug should be fixed in the next release
