### ISSUE TITLE
Environments should accept `.`

### ISSUE THREAD

**Issue by feinstein** [pingbird/puro#45]
We only use versions of Flutter that have been approved, so I want to only have in puro those versions.

Thus I want to create an environment for `3.0.7` but since environments names can't have `.` in the name, or start with a number, I need to name it `env_3_0_7` which looks weird.

It would be better if the environment names could accept a flutter version (start with numbers, accept `.`, `-`, `+`, etc.).

**Comment by pingbird** [comment]
Covered by https://github.com/pingbird/puro/issues/35 which is next on my todo list
