### ISSUE TITLE
repeating entries in puro ls

### ISSUE THREAD

**Issue by tksoh** [pingbird/puro#46]
Lately I noticed something strange. When changing to some environments, `puro ls` would show two identical entries on the new environment it switches to.

```
$ puro --version
[i] Puro 1.3.5 (distribution/windows-x64)
    Dart 2.19.5 (stable) (Mon Mar 20 17:09:37 2023 +0000) on "windows_x64"

$ puro ls
[i] Environments:
    * stable (stable / 3.13.4 / 367f9ea16b)
      beta   (not installed)
      master (not installed)
      legacy (stable / 3.7.12 / 4d9e56e694)
      v3_10  (stable / 3.10.5 / 796c8ef792)

    Use `puro create <name>` to create an environment, or `puro use <name>` to switch

$ puro use -g legacy
[✓] Set global default environment to `legacy`

$ puro ls
[i] Environments:
      stable (stable / 3.13.4 / 367f9ea16b)
      beta   (not installed)
      master (not installed)
    * legacy (stable / 3.7.12 / 4d9e56e694)
    * legacy (stable / 3.7.12 / 4d9e56e694)
      v3_10  (stable / 3.10.5 / 796c8ef792)

    Use `puro create <name>` to create an environment, or `puro use <name>` to switch

```

I'm on Windows 11, with git bash and VS code.

**Comment by pingbird** [comment]
Not sure what could cause this, are you able to reproduce it consistently? What about with `--no-color`?

**Comment by tksoh** [comment]
With puro 1.3.6 ...

```
$ puro version
[i] Puro 1.3.6 (distribution/windows-x64)
    Dart 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "windows_x64"

$ puro --no-color ls
[i] Environments:
      stable (stable / 3.13.4 / 367f9ea16b)
      beta   (not installed)
      master (not installed)
    * legacy (stable / 3.7.12 / 4d9e56e694)
    * legacy (stable / 3.7.12 / 4d9e56e694)
      v3_10  (stable / 3.10.5 / 796c8ef792)

    Use `puro create <name>` to create an environment, or `puro use <name>` to switch

```

**Comment by mselmanyildirim** [comment]
I experience this as well, consistently. Seems it happens with the global entry (v2_10_5).  
I get following response in a folder that does not have a local config:

    > puro ls
    [i] Environments:
      stable  (stable / 3.13.5 / 12fccda598)
      beta    (not installed)
      master  (not installed)
    * v2_10_5 (stable / 2.10.5 / 5464c5bac7)
    * v2_10_5 (stable / 2.10.5 / 5464c5bac7)
      v3_13_2 (stable / 3.13.2 / ff5b5b5fa6)
      v3_7_10 (stable / 3.7.10 / 4b12645012)

In another folder that has a local config:

    > puro ls
    [i] Environments:
      stable  (stable / 3.13.5 / 12fccda598)
      beta    (not installed)
      master  (not installed)
      v2_10_5 (stable / 2.10.5 / 5464c5bac7)
      v2_10_5 (stable / 2.10.5 / 5464c5bac7)
    * v3_13_2 (stable / 3.13.2 / ff5b5b5fa6)
      v3_7_10 (stable / 3.7.10 / 4b12645012)

When global setting is set to stable, it doesn't happen though:

    > puro ls
    [i] Environments:
    * stable  (stable / 3.13.5 / 12fccda598)
      beta    (not installed)
      master  (not installed)
      v2_10_5 (stable / 2.10.5 / 5464c5bac7)
      v3_13_2 (stable / 3.13.2 / ff5b5b5fa6)
      v3_7_10 (stable / 3.7.10 / 4b12645012)

My setup: Win 10,  PowerShell / git Bash

**Comment by pingbird** [comment]
Reproduced, just forgot to exclude the `default` folder when listing folders 😂 thanks guys!
