### ISSUE TITLE
Can not create environment, having error with Expand-Archive

### ISSUE THREAD

**Issue by mselmanyildirim** [pingbird/puro#47]
When I try to create an environment, via `Power Shell` on a Windows 10 machine, `puro` fails to create while raising the following error: 

    [E] powershell: Expand-Archive : The 'Expand-Archive' command was found in the module 'Microsoft.PowerShell.Archive', but the module
    could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Archive'.
    At line:1 char:1
    + Expand-Archive C:\Users\msiPC\.puro\shared\caches\ec975089acb540fc607 ...
    + ~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (Expand-Archive:String) [], CommandNotFoundException
        + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

I've run `Import-Module Microsoft.PowerShell.Archive` as suggested, but it didn't help. I've also tried to create environment with an elevated `Power Shell` as well as turning Windows Antivirus Realtime protection off, but I got the same error. Interestingly, I can create the environment via `git bash`. I'll try to use puro via `git bash` for a while, but I would be happy to use it with my daily driver `Power Shell`. Appreciate any suggestion.

Thanks for the effort on the tool `puro` btw. Seems very practical.

**Comment by pingbird** [comment]
Do you get an error when running `Import-Module Microsoft.PowerShell.Archive`?

This kind of sounds like a broken PowerShell environment, Expand-Archive is pretty bad so I think just ditching it in favor of 7-zip might be the way to go.

**Comment by pingbird** [comment]
Puro 1.3.6 now supports 7zip which should mitigate whatever problem you are experiencing

**Comment by mselmanyildirim** [comment]
> Do you get an error when running Import-Module Microsoft.PowerShell.Archive?

I don't get any error when running `Import-Module Microsoft.PowerShell.Archive`, but puro still can't have `Expand-Archive` work.

> Puro 1.3.6 now supports 7zip which should mitigate whatever problem you are experiencing..

I did have 7z, just added it to path, upgraded to puro 1.3.6, now puro can create environment even in PowerShell. Thank you very much!

**Comment by dhruvanbhalara** [comment]
I'm still facing the same issue with the latest version in windows 10.
```cmd
[E] powershell: Expand-Archive : A positional parameter cannot be found that accepts argument
    '.puro\shared\caches\09de023485e95e6d1225c2baa44b8feb85e0d45f.zip'.
    At line:1 char:45
    + ... ll.Archive; Expand-Archive C:\Users\Dhruvan Bhalara\.puro\shared\cach ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
        + FullyQualifiedErrorId : PositionalParameterNotFound,Expand-Archive
```
