### ISSUE TITLE
puro ls not indicating projects are using puro

### ISSUE THREAD

**Issue by tksoh** [pingbird/puro#49]
If we run `puro ls` in a project directory, it doesn't really tell us if the project is using puro, since the starred env could be just the global default. To confirm that, we will have to check on the `.puro.json` file.

Perhaps `puro ls` should put a special indicator to mark global default?

```
$ cd test_project

$ puro ls
[i] Environments:
    * stable (stable / 3.13.4 / 367f9ea16b)
      beta   (not installed)
      master (not installed)
      legacy (stable / 3.7.12 / 4d9e56e694)
      v3_10  (stable / 3.10.5 / 796c8ef792)

    Use `puro create <name>` to create an environment, or `puro use <name>` to switch

$ ls .puro.json
ls: cannot access '.puro.json': No such file or directory

$ puro use stable
[✓] Switched to environment `stable`

$ puro ls
[i] Environments:
    * stable (stable / 3.13.4 / 367f9ea16b)
      beta   (not installed)
      master (not installed)
      legacy (stable / 3.7.12 / 4d9e56e694)
      v3_10  (stable / 3.10.5 / 796c8ef792)

    Use `puro create <name>` to create an environment, or `puro use <name>` to switch

$ ls .puro.json
.puro.json


```

**Comment by pingbird** [comment]
An indicator for the global environment will be in the next release

**Comment by tksoh** [comment]
That's great.

BTW, just curious, if the global environment has been selected in a project, will there be some kind of indication too? Just thought it would be clearer to separate global from the selected one. That way we can tell if a project has been assigned the global somehow.

**Comment by tksoh** [comment]
... It may also 'protect' the projects using global from being switched unintentionally, shall we change the global later.

**Comment by pingbird** [comment]
The indicator is different depending on if the current environment is selected because of a project override `*`or the global default `~`
