### ISSUE TITLE
puro clean failed to remove SDK path from project's .vscode/settings.json

### ISSUE THREAD

**Issue by tksoh** [pingbird/puro#50]
This happens randomly, so I can't reproduce it reliably, but thought I should at least report it to keep a record this is happening.

As seen in the screenshot below, the project was set to use to v3_10. After `puro clean`,  with `puro ls` showing stable as the default env, `settings.json` still points to v3_10.

On Windows 11 + VS Code 1.18.2.

![Screenshot 2023-09-23 132734](https://github.com/pingbird/puro/assets/494222/4d4ad7d5-59aa-4fa5-8adc-b78fbcfcb411)

**Comment by tksoh** [comment]
BTW, running `puro clean` again would finally clean up the SDK settings

![Screenshot 2023-09-23 144656](https://github.com/pingbird/puro/assets/494222/a45de710-43cd-4e8c-b7ec-0d8b8c6c4eae)

**Comment by pingbird** [comment]
Puro saves the previous SDK paths and restores them when running `puro clean`, but I forgot to check if the SDK was managed by puro, this should be fixed in the next release.
