### ISSUE TITLE
Package Publish Fails 

### ISSUE THREAD

**Issue by getBoolean** [pingbird/puro#61]
I'm attempting to run `dart pub publish --dry-run` in my https://github.com/getBoolean/dart_holodex_api repo, but I am getting this error.

Tested on Windows 11

```
Resolving dependencies... 
Got dependencies!
Invalid argument (beneath): ../../../../dev/GitHub/dart_holodex_api: "must be relative and normalized"
package:pub/src/ignore.dart 229:7         Ignore.listFiles
package:pub/src/package.dart 232:19       Package.listFiles
package:pub/src/command/lish.dart 268:33  LishCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    C:\Users\Boolean\.puro\shared\pub_cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
```

**Comment by pingbird** [comment]
I was able to reproduce this issue on Windows when the dart_holodex_api folder is inside a symlink, it can also be reproduced without puro.

This appears to be a bug in the pub tool, I suggest filing an issue at https://github.com/dart-lang/pub/issues/new and as a workaround you can run the pub tool inside the real, non-symlinked path.

**Comment by getBoolean** [comment]
Hmm, thats odd. I don't think I have a symlink here. I'll create the issue.

**Comment by getBoolean** [comment]
My repo is not in a symlink, but I've created the issue

PowerShell script to check for symlinks:
```
$ ((get-item B:\dev).Attributes.ToString())
Directory
$ ((get-item B:\dev\GitHub).Attributes.ToString())
Directory
$ ((get-item B:\dev\GitHub\dart_holodex_api).Attributes.ToString())
Directory
```
