### ISSUE TITLE
Android Studio "Run" action ingores project flutter version

### ISSUE THREAD

**Issue by angelpinheiro** [pingbird/puro#73]
Hello! I'm giving Puro a try, and so far, my initial experience has been fantastic. I primarily use Android Studio, and I haven't encountered any issues while using Puro from the console. The IDE configuration is updated, and everything works fine. 

However, I've noticed that when I attempt to launch an app with a specific Flutter version using the "Run" action in Android Studio, it consistently utilizes the global Flutter version and ignores the specific project configuration. I'm curious if this is a known issue, or if it falls outside the scope of this tool.

**Comment by pingbird** [comment]
I have been fighting with this too it seem like the flutter/dart plugin ignores changes to the xml settings, I'm waiting on an official API for this that is less flaky: https://github.com/flutter/flutter-intellij/issues/6911

The workaround is to manually go into settings and set the dart sdk path to your desired environment:
![image](https://github.com/pingbird/puro/assets/2466461/11e1299a-79a0-442f-b228-be118c27e133)

**Comment by angelpinheiro** [comment]
Thanks, that's what I was doing. Congrats for your great work!
