### ISSUE TITLE
.puro.json is automatically ignored by git, any reason why is that the default?

### ISSUE THREAD

**Issue by HazemSayad** [pingbird/puro#76]
Trying to include my `.puro.json` file in my commits to lock the project to a specific flutter release using puro but i can't without manually doing it. So mainly my issue is about why is that? are there pros to not include it in version control?

using: `git check-ignore -v .puro.json`:
found: `.git/info/exclude:9:.puro.json  .puro.json` with:
```
# Managed by puro
.puro.json
```

then went to see if there are any more details about this in the puro manual and only was able to find that it is [automatically ignored](https://puro.dev/reference/manual/#switching-specific-projects)

**Comment by pingbird** [comment]
`.puro.json` is not meant to be shared because it can contain paths that are only valid on your computer, the functionality you want is tracked in https://github.com/pingbird/puro/issues/60 which would be stored in a separate file

**Comment by HazemSayad** [comment]
I see, thanks for your efforts :beers: 
feel free to close the issue if you like
