### ISSUE TITLE
Error setting certificate file

### ISSUE THREAD

**Issue by Spad8** [pingbird/puro#85]
I am trying to use this, but I get this error, any info?

puro create stable stable --log-level=4
[D] PURO_FLUTTER_BIN: null
[V] Started waiting for lock on path\of\puro\prefs.json
[V] Waiting for lock on path\of\puro\prefs.json took 0ms
[D] target: PuroBuildTarget.windowsX64
[D] Platform.executable: path\of\puro\bin\puro.exe
[D] Platform.resolvedExecutable: path\of\puro\bin\puro.exe
[D] Platform.script: file:///path\of\puro/puro.exe
[D] Platform.packageConfig: null
[D] No package root: Platform.packageConfig is null
[D] packageRoot: null
[D] executablePath: path\of\puro\puro.exe
[D] scriptPath:path\of\puro\puro.exe
[D] scriptExtension: .exe
[D] installationType: PuroInstallationType.distribution
[D] version: 1.4.6
[V] Checking if update is available
[V] Started waiting for lock on path\of\puro\latest_version
[V] Waiting for lock on path\of\puro\latest_version took 0ms
[D] lastNotification: null
[D] latestVersion: 1.4.6
[D] isOutOfDate: false
[D] willNotify: false
[D] shouldVersionCheck: false
[D] lastVersionCheck: 2024-06-01 23:00:23.823447
[V] Started waiting for lock on path\of\puro\releases_windows.json
[V] Waiting for lock on path\of\puro\releases_windows.json took 0ms
[V] Creating a new environment in path\of\puro\envs\stable
[V] Started waiting for lock on path\of\puro\envs\stable\update.lock
[V] Waiting for lock on path\of\puro\envs\stable\update.lock took 0ms
[V] Started waiting for lock on path\of\puro\envs\stable\prefs.json
[V] Waiting for lock on path\of\puro\envs\stable\prefs.json took 0ms
[V] Pre-caching engine...
[V] Cloning flutter with shared refs
[D] repository: path\of\puro\envs\stable\flutter
[D] flutterVersion: stable / 3.22.1 / a14f74ff3a
[D] forkRemoteUrl: stable / 3.22.1 / a14f74ff3a
[D] forkRef: null
[V] Started cloning https://github.com/flutter/flutter.git
[D] [git 7788] > git clone https://github.com/flutter/flutter.git --no-checkout --progress --shared path\of\puro\shared\flutter
[D] git: Cloning into 'path\of\puro\shared\flutter'...
[D] Pre-caching engine 55eae6864b296dd9f43b2cc7577ec256e5c32a8d
[V] Started checking if dart works
[D] > path\of\puro\shared\caches\55eae6864b296dd9f43b2cc7577ec256e5c32a8d\dart-sdk\bin\dart.exe --version
[V] Checking if dart works took 1ms
[W] dart version check failed, deleting cache
[V] Downloading engine
[V] Downloading https://storage.googleapis.com/flutter_infra_release/flutter/55eae6864b296dd9f43b2cc7577ec256e5c32a8d/dart-sdk-windows-x64.zip to path\of\puro\shared\caches\55eae6864b296dd9f43b2cc7577ec256e5c32a8d.zip
[V] Started downloading engine
[D] git: fatal: unable to access 'https://github.com/flutter/flutter.git/': error setting certificate file: C:\Git\mingw64\ssl\certs\ca-bundle.crt
[D] [git 7788] finished with exit code 128 in 106ms
[V] git failed with exit code 128
[V] Cloning https://github.com/flutter/flutter.git took 107ms
[/ / / / / / / /] Downloading engine
[x] Bad state: git subprocess failed with exit code 128
    #0      GitClient._ensureSuccess (package:puro/src/git.dart:109)
    #1      GitClient.clone (package:puro/src/git.dart:167)
    <asynchronous suspension>
    #2      GitClient.cloneWithProgress.<anonymous closure> (package:puro/src/git.dart:181)
    <asynchronous suspension>
    #3      ProgressNode.wrap (package:puro/src/progress.dart:68)
    <asynchronous suspension>
    #4      GitClient.cloneWithProgress (package:puro/src/git.dart:179)
    <asynchronous suspension>
    #5      fetchOrCloneShared (package:puro/src/env/create.dart:205)
    <asynchronous suspension>
    #6      cloneFlutterWithSharedRefs (package:puro/src/env/create.dart:332)
    <asynchronous suspension>
    #7      createEnvironment.<anonymous closure> (package:puro/src/env/create.dart:148)
    <asynchronous suspension>
    #8      lockFile (package:puro/src/file_lock.dart:68)
    <asynchronous suspension>
    #9      createEnvironment (package:puro/src/env/create.dart:109)
    <asynchronous suspension>
    #10     CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #11     main (package:puro/src/cli.dart:256)
    <asynchronous suspension>

[x] Puro crashed! Please file an issue at https://github.com/pingbird/puro

**Comment by yeikel16** [comment]
I have someting like that but with other error

```sh
PS C:\Users\uyeik\development> puro create "f3-22-1" --log-level=4
[D] PURO_FLUTTER_BIN: null
[V] Started waiting for lock on C:\Users\uyeik\.puro\prefs.json
[V] Waiting for lock on C:\Users\uyeik\.puro\prefs.json took 0ms
[D] target: PuroBuildTarget.windowsX64
[D] Platform.executable: C:\Users\uyeik\.puro\bin\puro.exe
[D] Platform.resolvedExecutable: C:\Users\uyeik\.puro\bin\puro.exe
[D] Platform.script: file:///C:/Users/uyeik/.puro/bin/puro.exe
[D] Platform.packageConfig: null
[D] No package root: Platform.packageConfig is null
[D] packageRoot: null
[D] executablePath: c:\users\uyeik\.puro\bin\puro.exe
[D] scriptPath: c:\users\uyeik\.puro\bin\puro.exe
[D] scriptExtension: .exe
[D] installationType: PuroInstallationType.distribution
[D] version: 1.4.6
[V] Checking if update is available
[V] Started waiting for lock on C:\Users\uyeik\.puro\latest_version
[V] Waiting for lock on C:\Users\uyeik\.puro\latest_version took 0ms
[D] lastNotification: null
[D] latestVersion: 1.4.6
[D] isOutOfDate: false
[D] willNotify: false
[D] shouldVersionCheck: false
[D] lastVersionCheck: 2024-06-03 10:42:18.063466
[V] Started fetching https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json
[/ / / / / / / /] Fetching https://storage.googleapis.com/flutter_infra_release/releases/releases[V] Fetching https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json took 396ms
[x] HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
    #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
    #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143)
    #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:920)
    #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049)
    <asynchronous suspension>

[x] Puro crashed! Please file an issue at https://github.com/pingbird/puro
```

**Comment by pingbird** [comment]
@Spad8
Your issue seems to be a problem with your git / mingw installation, the error is out of puro's control

@yeikel16
That looks like your OS doesn't have storage.googleapis.com in its certificate chain, this is also something out of puro's control, does `wget "https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json"` work?
