### ISSUE TITLE
bug: wrong distribution when install puro in windows arm

### ISSUE THREAD

**Issue by yeikel16** [pingbird/puro#86]
When install `puro` in windows 11 ARM is wrong the distribution label in the version info

```sh
[i] Puro 1.4.6 (distribution/windows-x64)
    Dart 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "windows_x64"
```
I using VMware in my **Macbook Pro M1** to run **Windows 11** with `Versión 23H2 (Compilación SO 22631.2861)`

**Comment by pingbird** [comment]
Flutter does not have a native arm64 sdk for windows (see https://docs.flutter.dev/release/archive?tab=windows), but it should still work with x86 emulation
