### ISSUE TITLE
Check if environment exists

### ISSUE THREAD

**Issue by mendoxe** [pingbird/puro#94]
Hi there, 

it would be greatly beneficial to have an option to check if an environment exists and if it has the correct version. There could also be a command that creates the environment only when it does not exist and ignores it when it exists.

**Comment by pingbird** [comment]
This can be done with jq:

```
> puro ls --json | jq -e '.environmentList.environments | .[] | select(.name == "stable")'
{
  "name": "stable",
  "path": "/home/ping/.puro/envs/stable",
  "version": {
    "commit": "67457e669f79e9f8d13d7a68fe09775fefbb79f4",
    "version": "3.16.8",
    "branch": "stable"
  },
  "projects": [
    "/c/Users/ping/IdeaProjects/ftest"
  ]
}
```

With -e, jq will return a non-zero exit code
